### ISSUE TITLE
regの初期値に定数以外の値が使われる場合がある

### ISSUE THREAD

**Issue by miya4649** [synthesijer/synthesijer#4]
以下のようなプログラムをコンパイルすると、
```
public class Test
{
  private int a = 12345;

  public void run()
  {
    int b = a;
  }
}
```

このような記述が出力されて、合成時に右辺が定数でないというエラーになります。
```
reg signed [32-1 : 0] run_b_0003 = class_a_0000;
```

以前のバージョンでは出ていなかったように思いますが、20150924バージョンで出ます。

**Comment by miyo** [comment]
ご連絡ありがとうございます．修正します．

**Comment by miyo** [comment]
該当コード部分をコメントアウトしました．近いうちにバイナリパッケージを作ります．

**Comment by miya4649** [comment]
git版で正常に合成でき、ブロック崩しのサンプルも実行できました。
ありがとうございます！

**Comment by miyo** [comment]
ご確認いただきまして，ありがとうございます!!Closeしますね．
