### ISSUE TITLE
ダウンロードサイトのsetupスクリプトが404エラー

### ISSUE THREAD

**Issue by miya4649** [synthesijer/synthesijer#8]
ダウンロードサイトのsetupスクリプトが404エラーでダウンロードできません。
具体的には
setup_20170322.sh
synthesijer_env_20170322.bat
がダウンロードできません。

**Comment by miyo** [comment]
ご指摘ありがとうございます．アップロードいたしました．

**Comment by miya4649** [comment]
ダウンロード、インストールできました。
ありがとうございます！
